language: ruby
rvm:
- 2.0.0-p598
- 2.1.5
- 2.2.2
addons:
  code_climate:
    secure: nYbre3WtdZCUnUnyX5wrw2YhmiGyrF2X0yVpaEpwCYWNE2S9wNO6gb1D5bPdz7IjAkinpSwJSN6Yjtvz2dPfWZhCcF+eBHgQw2cyVyBKrebWdnqAR64uuQfsH/MUOAYLRPl4uTEbVfFGR4Vw63WCN2ikLFVs6du+NV2w/muU+AQ=
